import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { getSession } from "@/auth/actions";
import { db } from "@/db";
import { redirect } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();

  try {
    const user = await db.user.findUnique({ where: { email: session.email } });

    if (!user) {
      throw new Error("User not found");
    }
  } catch (error) {
    console.error(error);
  }

  return (
    <html lang="en">
      <body className={`unselectable ${inter.className}`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
